### PR TITLE
4329b1 ip4 iOS 5.1.1

### PR DESCRIPTION
**Pull request by mmxx3**
added 
print '\firmware hash: ', diff_fname

visual view of the calculated hash

this are links to the firmware files

4329b1 ip4 iOS 5.1.1

bachelor-wapi.bin   sha1:bf344c8f6c821a912b5372a6bfffcb92b8b17072
http://db.tt/f9HincI9

bachelor.bin    sha1:19ce78843d7caad1abfee0fc5807e9dd275158f5
http://db.tt/QhpcE1Ic

### CODE REVIEW

**Comment by resistor4u** [comment]
is there any developments on this? i'm using the tool on an old jailbroken iphone 4 (7.1.2) i bought just to work this. when i run the patcher, i'm getting an invalid signature.

**Comment by 6e726d** [comment]
@resistor4u Sorry for the delay response.
This project is not being maintained. Probably the issue you are mentioning is because the patcher doesn't know that particular version of the firmware. The firmware patching process has to be done for an specific version of the firmware to avoid generating and invalid firmware that could leave a device without a wifi support.

**Comment by resistor4u** [comment]
@6e726d thanks for the response. i can try to debug it myself even though it's out of my skill set. can you provide the paths to the iphone 4 chipset firmware for the latest iOS you have?

**Comment by 6e726d** [comment]
Don't have a jailbroken IOS device at the moment, if you give me a couple of days I will try the latest stuff on a device I have at home.

**Comment by resistor4u** [comment]
@6e726d any news on your end? i've had some time to unpack ios 7.1.2 for iphone 4 (iphone 3,2). i know the project's not maintained, but i'd love to bring this up to date if possible, even though it's prolly beyond my skill set!

**Comment by 6e726d** [comment]
Sorry it took me so much, at the moment I don't have a Jailbroken Apple device. Creating a binary patch for the firmware it's not an easy task. Requires reversing the Broadcom chipset firmware, writing the patch using ARM assembly manually and perform tests without having debugging capabilities.

**Comment by resistor4u** [comment]
@6e726d totally understandable. personally, i'd like to try working through this as a hobby project. i think i have most of the correct tools and a sufficient understanding of the overall process. i hope to build on this tool and the nexmon project. if you could point me in the right direction for a starting point, that would be very helpful - i.e., what are the file paths for the iphone 3,2 that need the patches for ios 7.1.2. is this documented somewhere i haven't seen yet? if i understand the monmob project well enough, it seemed to work on iphone4 running ios5 and ios6, so if you know the file paths for those that could be a help too.

**Comment by 6e726d** [comment]
The paper and slides related to this project could help you with the firmware path and some ideas.

Slides - https://www.coresecurity.com/system/files/publications/2016/05/corelabs-BlancoEissler-2012-ekoparty.pdf
Paper - https://www.coresecurity.com/system/files/publications/2016/05/corelabs-BlancoEissler_2012-paper.pdf

**Pull request closed without merging**
